services:
  - type: web
    name: flask-ad-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PORT
        value: 10000
